### ISSUE TITLE
Spurious errors kvstore-test test suite

### ISSUE THREAD

**Issue by romac** [informalsystems/tendermint-rs#784]
On both current `master` and in #783, I am seeing some non-deterministic errors when running the `tendermint` test suite of the `kvstore-test` crate.

**Steps to reproduce**

From within the `tools/kvstore-test` directory, run the following commands a few times until an error appears:

1. `rm -rf /tmp/tendermint && mkdir /tmp/tendermint && rm -rf /tmp/tendermint && mkdir /tmp/tendermint && docker run -it --rm -v "/tmp/tendermint:/tendermint" -p 26657:26657 tendermint/tendermint:v0.34.0 node --proxy_app=kvstore`
2. `cargo test --test tendermint -- --nocapture`

**Errors seen so far**

1. `thread 'rpc::transaction_subscription' panicked at 'assertion failed: res.total_count > 0', kvstore-test/tests/tendermint.rs:382:9`
2. `rpc::commit' panicked at 'assertion failed: \`(left == right)\` left: \`false\`, right: \`true\`', kvstore-test/tests/tendermint.rs:146:9`

**Comment by thanethomson** [comment]
I haven't seen any of these nondeterministic failures in a few months now (I think due to increases in the timeout durations in the tests).

@mzabaluev have you seen any such failures in the past month or so? If so they would originate from [here](https://github.com/informalsystems/tendermint-rs/blob/master/tools/kvstore-test/tests/tendermint.rs).

**Comment by mzabaluev** [comment]
> @mzabaluev have you seen any such failures in the past month or so?

Sorry, I have not been running tendermint-rs tests lately.
